version: '3.8'
services:
  stats-server:
    build: ./statistics/stats-server/
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db

  stats-db:
    image: postgres:14-alpine
    ports:
      - "10050:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=stats-db
      - POSTGRES_PASSWORD=stats-db

  ewm-service:
    build: ./ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - STATS_SERVER_URL=http://stats-server:9090
      - APP_NAME=ewm-service

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "10051:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=ewm-db
      - POSTGRES_PASSWORD=ewm-db
